---
# Information in this playbook and associated roles is taken from 
# the access.redhat.com article which can be found at: 
# https://access.redhat.com/solutions/5793031

- name: Seal an Enterprise Linux VM to Prepare it as a Template
  hosts: all
  become: true

  roles:
    - role: unsubscribe
      when: ansible_distribution == 'RedHat'
    - role: reset_nic 
    - role: reset_nic 
    - role: hostname
      vars:
        new_hostname: 'localhost.localdomain'
    - role: remove_host_keys
    - role: remove_unique_id_89
    - role: remove_satellite
    - role: remove_iscsi_init


